CadastroContatos/Models/ContatoModel.cs
using System.ComponentModel.DataAnnotations;

namespace CadastroContatos.Models
{
    /*
     * Descreve as propriedades do objeto
     */
    public class ContatoModel
    {
        /*
         * Propriedades
         */
        public int id { get; set; }

        // VALIDAÇÕES CAMPO NOME
        [Required(ErrorMessage = "O campo NOME é obrigatório!")]
        public string Nome { get; set; }

        // VALIDAÇÕES CAMPO EMAIL
        [Required(ErrorMessage = "O campo EMAIL é obrigatório!")]
        [EmailAddress(ErrorMessage = "O Email informado não é válido!")]
        public string Email { get; set; }

        // VALIDAÇÕES CAMPO WHATSAPP
        [Required(ErrorMessage = "O campo WHATSAPP é obrigatório!")]
        [Phone(ErrorMessage = "O celular informado não é válido!")]
        public string WhatsApp { get; set; }    

    }
}

CadastroContatos/Models/ErrorViewModel.cs
using System;

namespace CadastroContatos.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CadastroContatos/Controllers/ContatoController.cs
using CadastroContatos.Models;
using CadastroContatos.Repository;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace CadastroContatos.Controllers
{
    public class ContatoController : Controller
    {
        /*
         *  Constructor 
         */
        private readonly IContatoRepositorio _contatoRepositorio;
        public ContatoController(IContatoRepositorio contatoRepositorio)
        {
            _contatoRepositorio = contatoRepositorio;
        }

        /*
         * Controller Index GET
         * Busca todos os contatos
         */
        public IActionResult Index()
        {
            List<ContatoModel> contatos = _contatoRepositorio.BuscarTodos();
            return View(contatos);
        }


        /*
         * Controller Criar GET
         * Retorna View
         */
        public IActionResult Criar()
        {
            return View();
        }


        /*
         * Controller Criar POST
         * Salva o objeto de contato 
         */
        [HttpPost]
        public IActionResult Criar(ContatoModel contato)
        {
            /*
             * Só deixa tentar salvar no banco
             * caso a model state esteja válida
             */
            try
            {
                if (ModelState.IsValid)
                {
                    // chama metodo Adiconar criado no Repositorio
                    _contatoRepositorio.Adicionar(contato);
                    TempData["MensagemSucesso"] = "Contato cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View(contato);
            }
            catch (System.Exception erro)
            {

                TempData["MensagemErro"] = $"Erro ao cadastrar! erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }


        /*
         * Controller Editar GET
         * Retorna a view
         */
        public IActionResult Editar(int id)
        {
            ContatoModel contato = _contatoRepositorio.ListarPorId(id);    
            return View(contato);

        }

        /*
         * Controller Editar POST
         * Salva o objeto de contato 
         */
        [HttpPost]
        public IActionResult Editar(ContatoModel contato)
        {
            /*
              * Só deixa tentar atyalizar no banco
              * caso a model state esteja válida
              */
            try
            {
                if (ModelState.IsValid)
                {
                    // chama metodo Adiconar criado no Repositorio
                    _contatoRepositorio.Atualizar(contato);
                    TempData["MensagemSucesso"] = "Contato atualizado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View(contato);
            }
            catch (System.Exception erro)
            {

                TempData["MensagemErro"] = $"Erro ao atualizar! erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        /*
         * Controller Confirmação de apagar GET
         * Retorna a view
         */
        public IActionResult ApagarConfirm(int id)
        {
            ContatoModel contato = _contatoRepositorio.ListarPorId(id);
            return View(contato);
        }

        /*
         * Controller apagar GET
         * Retorna a view
         */
        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagado = _contatoRepositorio.Apagar(id);
                if (apagado) {
                    TempData["MensagemSucesso"] = "Contato apagado!";
                }
                else
                {
                    TempData["MensagemErro"] = "Erro ao apagar!";
                }

                return RedirectToAction("Index");
            }
            catch(System.Exception erro)
            {
                TempData["MensagemErro"] = $"Erro ao apagar! erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

CadastroContatos/Controllers/HomeController.cs
using CadastroContatos.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CadastroContatos.Controllers
{
    public class HomeController : Controller
    {


        /*
         * Controller Index GET
         * Retorna a view
         */
        public IActionResult Index()
        {
            return View();
        }



        /*
         * Controller Erro
         */
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CadastroContatos/Views/Contato - Copy/Criar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

CadastroContatos/Views/Contato - Copy/Index.cshtml
@{
    ViewData["Title"] = "Lista";
}

<div class="text-center">

    <h1 class="display-4">Contatos</h1>
    <br />
    <div class="d-grid gap-2 d-md-flex justify-content-md-center">
        <a class="btn btn-outline-primary text-primary">Adicionar contato</a>
    </div>
    <br />
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Email</th>
                <th scope="col">WhatsApp</th>
                <th scope="col">Ação</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>Mark</td>
                <td>Otto@gmail.com</td>
                <td>61 9 8248-1642</td>
                <td>
                    <div class="btn-group" role="group" aria-label="Ações">
                        <a role="button" class="btn btn-success text-white">Editar</a>
                        <a role="button" class="btn btn-danger text-white">Excluir</a>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</div>

CadastroContatos/Views/Contato/ApagarConfirm.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Apagar " + @Model.Nome;
}

<div class="text-center">

    <h1 class="display-4">Realmente quer apagar o<br />contato @Model.Nome?</h1>
    <br />
    @*
        Buttons
    *@
    <a class="btn btn-primary"
       asp-route-id="@Model.id"
       asp-controller="Contato"
       asp-action="Apagar">Remover</a>

    <a class="btn btn-outline-secondary"
       asp-controller="Contato"
       asp-action="Index">Cancelar</a>

</div>

CadastroContatos/Views/Contato/Criar.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Adicionar";
}

<div class="text-center">

    <h1 class="display-4">Adicionar novo</h1>

</div>

<form asp-controller="Contato" asp-action="Criar" method="post">
    @*
        Input Nome
    *@
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text"
               id="nome"
               class="form-control"
               placeholder="Jonh Doe" 
               asp-for="Nome"/>
        @Html.ValidationMessageFor(x => x.Nome)
    </div>
    @*
        Input Email
    *@
    <div class="form-group">
        <label for="email">Email</label>
        <input type="text"
               id="email"
               class="form-control"
               placeholder="jonh.doe@mail.com"
               asp-for="Email"/>
        @Html.ValidationMessageFor(x => x.Email)
    </div>
    @*
        Input WhatsApp
    *@
    <div class="form-group">
        <label for="wpp">WhatsApp</label>
        <input type="text"
               id="wpp"
               class="form-control"
               placeholder="(00) 9999-9999" 
               asp-for="WhatsApp"/>
        @Html.ValidationMessageFor(x => x.WhatsApp)
    </div>
    @*
        Buttons Form
    *@
    <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
    <a class="btn btn-outline-secondary btn-block" asp-controller="Contato" asp-action="Index">Voltar</a>
</form>

CadastroContatos/Views/Contato/Criar/rowContato.cshtml
@model ContatoModel
<tr>
    <th scope="row">@Model.id</th>
    <td>@Model.Nome</td>
    <td>@Model.Email</td>
    <td>@Model.WhatsApp</td>
    <td>
        <div class="btn-group" role="group" aria-label="Ações">
            <a role="button"
                class="btn btn-success"
                asp-route-id="@Model.id"
                asp-controller="Contato"
                asp-action="Editar">
                Editar
            </a>

            <a role="button"
                class="btn btn-danger"
                asp-route-id="@Model.id"
                asp-controller="Contato"
                asp-action="ApagarConfirm">
                Excluir
            </a>
        </div>
    </td>
</tr>

CadastroContatos/Views/Contato/Editar.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Editar";
}

<div class="text-center">

    <h1 class="display-4">Editar</h1>

</div>

<form asp-controller="Contato" asp-action="Editar" method="post">
    @*
        Id
    *@
    <input type="hidden" asp-for="id" />
    @*
        Input Nome
    *@
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text"
               id="nome"
               class="form-control"
               placeholder="Jonh Doe" 
               asp-for="Nome"/>
        @Html.ValidationMessageFor(x => x.Nome)
    </div>
    @*
        Input Email
    *@
    <div class="form-group">
        <label for="email">Email</label>
        <input type="text"
               id="email"
               class="form-control"
               placeholder="jonh.doe@mail.com"
               asp-for="Email"/>
        @Html.ValidationMessageFor(x => x.Email)
    </div>
    @*
        Input WhatsApp
    *@
    <div class="form-group">
        <label for="wpp">WhatsApp</label>
        <input type="text"
               id="wpp"
               class="form-control"
               placeholder="(00) 9999-9999" 
               asp-for="WhatsApp"/>
        @Html.ValidationMessageFor(x => x.WhatsApp)

    </div>
    @*
        Buttons Form
    *@
    <button type="submit" class="btn btn-primary btn-block">Atualizar</button>
    <a class="btn btn-outline-secondary btn-block" asp-controller="Contato" asp-action="Index">Voltar</a>
</form>

CadastroContatos/Views/Contato/Index.cshtml
@model List<ContatoModel>
@{
    ViewData["Title"] = "Lista";
}

<div class="text-center">

    <partial name="global/alert" />

    <br />

    <h1 class="display-4">Contatos</h1>

    <br />
    <div class="d-grid gap-2 d-md-flex justify-content-md-center">
        <a class="btn btn-outline-primary text-primary"
           asp-controller="Contato"
           asp-action="Criar">
            Adicionar contato
        </a>
    </div>
    <br />
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Email</th>
                <th scope="col">WhatsApp</th>
                <th scope="col">Ação</th>
            </tr>
        </thead>
        <tbody>
            @*
                Valida se existe o model
            *@
            @if (Model != null && Model.Any())
            {
                @*
                    Passa por todos os contatos
                    e passa o objeto de contato
                    para a partial rowContato
                *@
                foreach (ContatoModel contato in Model)
                {
                    <partial name="Criar/rowContato" model="@contato" />
                }
            }

        </tbody>
    </table>
</div>

CadastroContatos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Inicio";
}

<div class="banner">
    <h1 class="display-4">Bem vindo ;)</h1>
</div>

CadastroContatos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Contatinhos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-0">
            <div class="container">
@*
                Titulo
*@
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                   <b>All Names</b>
                </a>
                <br />
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
@*
                Menus
*@
                <div class="nav navbar-collapse collapse d-sm-inline-flex justify-content-end">
                    <ul class="navbar-nav flex-grow-1 flex-row-reverse">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">Contatos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


@*
                Footer
*@
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Contatinhos
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CadastroContatos/Views/Shared/global/alert.cshtml
@*
    Component
*@

@if(TempData["MensagemSucesso"] != null || TempData["MensagemErro"] != null)
{
    <div class="alert alert-@(TempData["MensagemSucesso"] != null ? "success" : "danger")" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="close">X</button>
        @TempData["MensagemSucesso"]
        @TempData["MensagemErro"]
    </div>  
}